undefined reference to `dlopen' `dlsym' and others (#2)
* undefined reference to `dlopen' `dlsym' and others

swapped $(C1D) and $(F)

* warning on #import

changed to #include